BOOTMAGIC_ENABLE = no
SRC += matrix.c
BOARD = GENERIC_RP_RP2040
LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes
CUSTOM_MATRIX = yes
CONSOLE_ENABLE = yes
ENCODER_ENABLE = yes
RAW_ENABLE = yes
WPM_ENABLE = yes

DEBOUNCE_TYPE = asym_eager_defer_pk

OLED_ENABLE = yes
OLED_DRIVER_ENABLE = yes
OLED_DRIVER = GU7000
